### ISSUE TITLE
Reading in a .csv into Oracle - ERROR ReplicaDB:136 Got exception running ReplicaDB

### ISSUE THREAD

**Issue by jmcookle** [osalvador/ReplicaDB#107]
I am using the latest revision.

source.connect=file://C:\\ReplicaDB\\files\HRL_DM_KEYS_ITEM_JMC_ALL_25651455.csv
source.columns=KEY, ITEMBASEPEOORGANIZATIONID, ITEMBASEPEOLASTUPDATEDATE, ITEMBASEPEOINVENTORYITEMID, KEY2
source.connect.format=DEFAULT
source.connect.parameter.columns.types=integer, integer, varchar, integer, integer
source.connect.parameter.format.firstRecordAsHeader=true
source.connect.parameter.format=DEFAULT
source.connect.parameter.format.delimiter=,
source.connect.parameter.format.recordSeparator=\n
source.connect.parameter.format.firstRecordAsHeader=true
source.connect.parameter.format.ignoreEmptyLines=true
source.connect.parameter.format.nullString=
source.connect.parameter.format.ignoreSurroundingSpaces=true
source.connect.parameter.format.trim=true
sink.connect=jdbc:oracle:thin:@DHFC.WORLD

I am trying to read in a .csv into Oracle.  No matter what options I set on any CSV, I get the following error:

2022-11-06 14:08:42,208 ERROR ReplicaDB:136 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: superclass access check failed: class org.replicadb.rowset.CsvCachedRowSetImpl (in unnamed module @0x646be2c3) cannot access class com.sun.rowset.CachedRowSetImpl (in module java.sql.rowset) because module java.sql.rowset does not export com.sun.rowset to unnamed module @0x646be2c3
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:117) [ReplicaDB-0.13.0.jar:0.13.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.13.0.jar:0.13.0]
Caused by: java.lang.IllegalAccessError: superclass access check failed: class org.replicadb.rowset.CsvCachedRowSetImpl (in unnamed module @0x646be2c3) cannot access class com.sun.rowset.CachedRowSetImpl (in module java.sql.rowset) because module java.sql.rowset does not export com.sun.rowset to unnamed module @0x646be2c3
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at org.replicadb.manager.file.CsvFileManager.init(CsvFileManager.java:207) ~[ReplicaDB-0.13.0.jar:0.13.0]
        at org.replicadb.manager.LocalFileManager.makeSourceConnection(LocalFileManager.java:53) ~[ReplicaDB-0.13.0.jar:0.13.0]
        at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:103) ~[ReplicaDB-0.13.0.jar:0.13.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:43) ~[ReplicaDB-0.13.0.jar:0.13.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:15) ~[ReplicaDB-0.13.0.jar:0.13.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
2022-11-06 14:08:42,242 INFO  ReplicaDB:54 Total process time: 1091ms

This is the sample data I have in my CSV:
KEY,ITEMBASEPEOORGANIZATIONID,ITEMBASEPEOLASTUPDATEDATE,ITEMBASEPEOINVENTORYITEMID,KEY2
202112,300001621140062,2021-12-13T21:27:14.901+00:00,300000383134546,202112
202112,300001621140062,2021-12-13T21:26:55.100+00:00,300000383134564,202112
202112,300000117868180,2021-12-17T15:41:50.009+00:00,100000694427502,202112
202112,300000117868164,2021-12-17T15:41:59.034+00:00,100000694427503,202112

Any suggestions?   Thank you

**Comment by jmcookle** [comment]
I switched over to Linux and it worked fine.  Seems to be a windows only issue.

**Comment by osalvador** [comment]
Hi @jmcookle,

I think this is due to the JDK version and its vendor. I am working on upgrading to Java 11 and removing the deprecated Java 8 dependencies. 

Thanks for the report.
Regards
