### ISSUE TITLE
sql server Incremental mode and primary keys

### ISSUE THREAD

**Issue by giladfapri** [osalvador/ReplicaDB#11]
Incremental mode is not working if the sink table has identity column with auto increment, i need to set identity_insert to on before insert

**Comment by osalvador** [comment]
Thanks @giladfapri,

I need to test this bug.

**Comment by dom-centennial** [comment]
Thanks for the prompt update.
Works when no Identity column now, but does not work when there is
The SET IDENTITY_INSERT should do the trick 
see details below

/****** Object:  Table [dbo].[tblTaskLabour]    Script Date: 10/11/2020 6:44:14 AM ******/
CREATE TABLE [dbo].[tblTaskLabour](
[WorkloadDate] [datetime] NOT NULL,
[WorkloadShiftID] [int] NOT NULL,
[WorkloadAreaID] [int] NOT NULL,
[WorkloadPriority] [int] NOT NULL,
[WorkloadLabourID] [int] NOT NULL,
[WorkloadLabourNum] [int] NOT NULL,
[WorkloadLabourHrs] [decimal](10, 2) NULL,
[RecurTaskID] [int] NULL,
[Created] [datetime] NULL,
[CreatedBy] [nvarchar](max) NULL,
[ID] [int] IDENTITY(1,1) NOT NULL,
[LastModified] [datetime] NULL,
[LastModifiedBy] [nvarchar](max) NULL,
 CONSTRAINT [PK_tblTaskLabour] PRIMARY KEY CLUSTERED 
(
[WorkloadDate] ASC,
[WorkloadShiftID] ASC,
[WorkloadAreaID] ASC,
[WorkloadPriority] ASC,
[WorkloadLabourID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[tblTaskLabour] ADD  CONSTRAINT [DF__tblTaskLa__Creat__69D19EED]  DEFAULT (getdate()) FOR [Created]
GO

ALTER TABLE [dbo].[tblTaskLabour] ADD  CONSTRAINT [DF__tblTaskLa__Creat__6AC5C326]  DEFAULT (suser_sname()) FOR [CreatedBy]
GO

######### dbo.tblTaskLabour ###########
2020-11-09 19:38:56,487 INFO  ReplicaDB:42 Running ReplicaDB version: 0.8.9
2020-11-09 19:38:56,489 INFO  ReplicaDB:46 Setting verbose mode
2020-11-09 19:38:56,494 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-11-09 19:38:56,496 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-11-09 19:38:56,546 DEBUG SqlManager:269 No connection parameters specified. Using regular API for making connection.
2020-11-09 19:38:56,729 INFO  SQLServerManager:130 Creating staging table with this command:  SELECT * INTO dbo.tblTaskLabourrepdb5810 FROM dbo.tblTaskLabour WHERE 0 = 1
2020-11-09 19:38:56,740 INFO  SqlManager:386 Truncating sink table with this command: TRUNCATE TABLE dbo.tblTaskLabourrepdb5810
2020-11-09 19:38:56,748 INFO  ReplicaTask:36 Starting TaskId-0
2020-11-09 19:38:56,749 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-11-09 19:38:56,749 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-11-09 19:38:56,749 DEBUG SqlManager:212 No connection parameters specified. Using regular API for making connection.
2020-11-09 19:38:57,571 DEBUG SqlManager:269 No connection parameters specified. Using regular API for making connection.
2020-11-09 19:38:57,625 DEBUG SqlManager:131 TaskId-0: Using fetchSize for next query: 100
2020-11-09 19:38:57,633 INFO  SqlManager:141 TaskId-0: Executing SQL statement: SELECT  * FROM dbo.tblTaskLabour where LastModified >= '2020-11-10T06:33:54Z' AND LastModified <= '2020-11-10T06:38:54Z' AND 0 = ?
2020-11-09 19:38:57,633 INFO  SqlManager:148 TaskId-0: With args: 0,
2020-11-09 19:38:57,935 INFO  SQLServerManager:95 Perfoming BulkCopy into dbo.tblTaskLabourrepdb5810
2020-11-09 19:38:57,959 WARN  ConnManager:187 Options source-columns and sink-columns are null, getting from Source ResultSetMetaData: WorkloadDate,WorkloadShiftID,WorkloadAreaID,WorkloadPriority,WorkloadLabourID,WorkloadLabourNum,WorkloadLabourHrs,RecurTaskID,Created,CreatedBy,ID,LastModified,LastModifiedBy
2020-11-09 19:38:57,961 INFO  SQLServerManager:46 IF OBJECTPROPERTY(OBJECT_ID('dbo.tblTaskLabour'), 'TableHasIdentity') = 1 SET IDENTITY_INSERT dbo.tblTaskLabour ON
2020-11-09 19:38:57,982 INFO  SqlManager:331 Getting PKs for schema: dbo and table: tblTaskLabour. Found.
2020-11-09 19:38:57,983 INFO  SQLServerManager:192 Merging staging table and sink table with this command: MERGE INTO dbo.tblTaskLabour trg USING (SELECT WorkloadDate,WorkloadShiftID,WorkloadAreaID,WorkloadPriority,WorkloadLabourID,WorkloadLabourNum,WorkloadLabourHrs,RecurTaskID,Created,CreatedBy,ID,LastModified,LastModifiedBy FROM dbo.tblTaskLabourrepdb5810 ) src ON  (src.WorkloadDate= trg.WorkloadDate AND src.WorkloadShiftID= trg.WorkloadShiftID AND src.WorkloadAreaID= trg.WorkloadAreaID AND src.WorkloadPriority= trg.WorkloadPriority AND src.WorkloadLabourID= trg.WorkloadLabourID ) WHEN MATCHED THEN UPDATE SET  trg.WorkloadLabourNum = src.WorkloadLabourNum , trg.WorkloadLabourHrs = src.WorkloadLabourHrs , trg.RecurTaskID = src.RecurTaskID , trg.Created = src.Created , trg.CreatedBy = src.CreatedBy , trg.ID = src.ID , trg.LastModified = src.LastModified , trg.LastModifiedBy = src.LastModifiedBy  WHEN NOT MATCHED THEN INSERT ( WorkloadDate,WorkloadShiftID,WorkloadAreaID,WorkloadPriority,WorkloadLabourID,WorkloadLabourNum,WorkloadLabourHrs,RecurTaskID,Created,CreatedBy,ID,LastModified,LastModifiedBy ) VALUES ( src.WorkloadDate , src.WorkloadShiftID , src.WorkloadAreaID , src.WorkloadPriority , src.WorkloadLabourID , src.WorkloadLabourNum , src.WorkloadLabourHrs , src.RecurTaskID , src.Created , src.CreatedBy , src.ID , src.LastModified , src.LastModifiedBy  );
2020-11-09 19:38:57,985 ERROR ReplicaDB:101 Got exception running ReplicaDB:
com.microsoft.sqlserver.jdbc.SQLServerException: Cannot update identity column 'ID'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:711) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at org.replicadb.manager.SQLServerManager.mergeStagingTable(SQLServerManager.java:193) ~[ReplicaDB-0.8.9.jar:0.8.9]
        at org.replicadb.manager.SqlManager.postSinkTasks(SqlManager.java:521) ~[ReplicaDB-0.8.9.jar:0.8.9]
        at org.replicadb.manager.SQLServerManager.postSinkTasks(SQLServerManager.java:259) ~[ReplicaDB-0.8.9.jar:0.8.9]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:94) [ReplicaDB-0.8.9.jar:0.8.9]
2020-11-09 19:38:57,988 INFO  SqlManager:475 Dropping staging table with this command: DROP TABLE dbo.tblTaskLabourrepdb5810
2020-11-09 19:38:57,994 INFO  ReplicaDB:124 Total process time: 1514ms

**Comment by taher843** [comment]
How do I configure for a sql server table that doesn't have identity column ?
