### ISSUE TITLE
sql server sync bcp invalid column length

### ISSUE THREAD

**Issue by john-mizell** [osalvador/ReplicaDB#117]
**Describe the bug**
Using a complete table sync.

```
DEBUG SQLServerManager:95 Performing BulkCopy into DEVICE
2023-01-11 20:08:11,941 ERROR ReplicaTask:69 ERROR in TaskId-0 inserting data to sink table: [Received an invalid column length from the bcp client for colid 10.]
2023-01-11 20:08:11,942 ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: com.microsoft.sqlserver.jdbc.SQLServerException: Received an invalid column length from the bcp client for colid 10.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_352]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_352]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:115) [ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.0.jar:0.15.0]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Received an invalid column length from the bcp client for colid 10.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:258) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:104) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1517) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$300(SQLServerBulkCopy.java:65) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:649) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:683) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1581) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeResultSet(SQLServerBulkCopy.java:582) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:520) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at org.replicadb.manager.SQLServerManager.insertDataToTable(SQLServerManager.java:101) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:65) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:15) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Source table DDL
```sql
CREATE TABLE [dbo].[DEVICE](
	[FIELD1] [int] IDENTITY(1,1) NOT NULL,
	[FIELD2] [varchar](50) NULL,
	[FIELD3] [int] NOT NULL,
	[FIELD4] [int] NOT NULL,
	[FIELD5] [int] NULL,
	[FIELD6] [bit] NOT NULL,
	[FIELD7] [smallint] NULL,
	[FIELD8] [varchar](20) NULL,
	[FIELD9] [nvarchar](30) NULL,
	[FIELD10] [char](9) NULL,
	[FIELD11] [datetime2](7) NOT NULL,
	[FIELD12] [int] NOT NULL,
	[FIELD13] [smallint] NULL,
	[FIELD14](16) NULL,
	[FIELD15] [bit] NOT NULL,
	[FIELD16] [datetime2](7) NOT NULL,
	[FIELD17] [tinyint] NOT NULL,
	[FIELD18] [datetime2](7) NULL,
	[FIELD19] [datetime2](7) NULL,
	[FIELD20] [int] NULL,
	[FIELD21] [bit] NULL,
	[FIELD22] [varchar](70) NULL,
	[FIELD23] [tinyint] NULL,
	[FIELD24] [tinyint] NULL,
	[FIELD25] [tinyint] NULL,
	[FIELD26] [int] NULL,
	[FIELD27] [varchar](50) NULL,
	[FIELD28] [varchar](3) NOT NULL,
	[FIELD29] [varchar](3) NOT NULL,
	[FIELD30] [bit] NOT NULL,
	[FIELD31] [bit] NOT NULL,
 CONSTRAINT [PK_FIELD1] PRIMARY KEY CLUSTERED 
(
	[FIELD1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

3. Sink table DDL

```sql
CREATE TABLE [dbo].[DEVICE](
	[FIELD1] [int] IDENTITY(1,1) NOT NULL,
	[FIELD2] [varchar](50) NULL,
	[FIELD3] [int] NOT NULL,
	[FIELD4] [int] NOT NULL,
	[FIELD5] [int] NULL,
	[FIELD6] [bit] NOT NULL,
	[FIELD7] [smallint] NULL,
	[FIELD8] [varchar](20) NULL,
	[FIELD9] [nvarchar](30) NULL,
	[FIELD10] [char](9) NULL,
	[FIELD11] [datetime2](7) NOT NULL,
	[FIELD12] [int] NOT NULL,
	[FIELD13] [smallint] NULL,
	[FIELD14](16) NULL,
	[FIELD15] [bit] NOT NULL,
	[FIELD16] [datetime2](7) NOT NULL,
	[FIELD17] [tinyint] NOT NULL,
	[FIELD18] [datetime2](7) NULL,
	[FIELD19] [datetime2](7) NULL,
	[FIELD20] [int] NULL,
	[FIELD21] [bit] NULL,
	[FIELD22] [varchar](70) NULL,
	[FIELD23] [tinyint] NULL,
	[FIELD24] [tinyint] NULL,
	[FIELD25] [tinyint] NULL,
	[FIELD26] [int] NULL,
	[FIELD27] [varchar](50) NULL,
	[FIELD28] [varchar](3) NOT NULL,
	[FIELD29] [varchar](3) NOT NULL,
	[FIELD30] [bit] NOT NULL,
	[FIELD31] [bit] NOT NULL,
 CONSTRAINT [PK_FIELD1] PRIMARY KEY CLUSTERED 
(
	[FIELD1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

5. ReplicaDB configuration `options-file`. 

```properties
######################## ReplicadB General Options ########################
mode=complete
jobs=1
fetch.size=10000
verbose=true
## Help us to improve by activating usage analysis through the Sentry service. Or set up your own Sentry DSN
#sentry.dsn=https://400e0daa08c24a399b842048c409416f@o1002451.ingest.sentry.io/5962725
############################# Soruce Options ##############################
source.connect=jdbc:sqlserver://server1:1433;database=db1
source.user=myuser	
source.password=mypassword
source.table=DEVICE
############################# Sink Options ################################
sink.connect=jdbc:sqlserver://server2:1433;database=db2
sink.user=myuser
sink.password=mypassword
sink.table=DEVICE
sink.staging.schema=dbo
sink.disable.truncate=true
```

**Expected behavior**
I expected the data to sync

**Additional context**
Add any other context about the problem here. Running environment (cloud, on premise, java version..), source and sink technologies (Oracle, MySQL, Postgres...)
Sql server running in aws rds.java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment Corretto-8.352.08.1 (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM Corretto-8.352.08.1 (build 25.352-b08, mixed mode)

**Comment by osalvador** [comment]
Hi @john-mizell 

I was working on your issue and saw that there is a bug in the MS SQL Server driver, similar to this one
https://github.com/microsoft/mssql-jdbc/issues/1376 . The error occurs with fields with data type `[datetime2](7)`. I will open an issue in the mssql-jdbc project to report it. 

For the time being, and as a workaround, you can change the fields in the sink table from `datetime2` to `datetime`. You will lose the nanosecond precision for milliseconds. I've tested it and it works:

Source table: 

`select * From source_table` 

| FIELD10 | FIELD11 | 
| -- | -- | 
| 1         | 2023-01-12 12:38:33.1234567 | 


Sink table with `datetime` instead of `datetime2`  fields after the replication : 

`select * From sink_table` 

| FIELD10 | FIELD11 | 
| -- | -- | 
| 1        | 2023-01-12 12:38:33.123 |
