### ISSUE TITLE
Problems with sink staging schema when using SQLite

### ISSUE THREAD

**Issue by shatteringlass** [osalvador/ReplicaDB#123]
**Describe the bug**
SQlite as sink is not working due to apparent issues with the staging schema. This is what the program prints out (I've edited out sensitive info about the source).

```
2023-01-30 18:06:24,459 INFO  ReplicaDB:63 Running ReplicaDB version: 0.15.0
2023-01-30 18:06:24,561 INFO  ReplicaDB:66 Setting verbose mode DEBUG
2023-01-30 18:06:24,561 DEBUG ReplicaDB:67 ToolOptions{ 
	sourceConnect='jdbc:oracle:thin:@***::***',
	sourceUser='****',
	sourcePassword='****',
	sourceTable='***',
	sourceColumns='null',
	sourceWhere='creation_date >= current_date() - interval '7' days',
	sourceQuery='null',
	sinkConnect='jdbc:sqlite://database/test.db',
	sinkUser='null',
	sinkPassword='null',
	sinkTable='t_test_obj',
	sinkStagingTable='null',
	sinkStagingSchema='null',
	sinkStagingTableAlias='null',
	sinkColumns='null',
	sinkDisableEscape=false,
	sinkDisableIndex=false,
	sinkDisableTruncate=false,
	sinkAnalyze=false,
	jobs=4,
	BandwidthThrottling=0,
	quotedIdentifiers=false,
	fetchSize=1000,
	help=false,
	version=false,
	verbose=DEBUG,
	optionsFile='/tmp/secrets/replicadb.conf',
	mode='incremental',
	sentryDsn='null',
	sourceConnectionParams={ApplicationName=ReplicaDB},
	sinkConnectionParams={},
	sourceFileFormat='null',
	sinkFileformat='null'}
2023-01-30 18:06:26,163 WARN  SqlManager:482 No staging schema is defined, setting it as PUBLIC
2023-01-30 18:06:30,164 INFO  SqliteManager:230 Creating staging table with this command:  CREATE TABLE public.t_test_objrepdb7610 AS SELECT * FROM t_test_obj WHERE 1 = 0 
2023-01-30 18:06:30,169 ERROR ReplicaDB:134 Got exception running ReplicaDB:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (unknown database public)
	at org.sqlite.core.DB.newSQLException(DB.java:1030) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:1042) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.DB.throwex(DB.java:1007) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.NativeDB._exec_utf8(Native Method) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.NativeDB._exec(NativeDB.java:97) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.replicadb.manager.SqliteManager.createStagingTable(SqliteManager.java:231) ~[ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.manager.SqlManager.preSinkTasks(SqlManager.java:485) ~[ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:94) [ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.0.jar:0.15.0]
2023-01-30 18:06:30,360 INFO  SqlManager:462 Dropping staging table with this command: DROP TABLE public.t_test_objrepdb7610
2023-01-30 18:06:30,391 ERROR ReplicaDB:156 org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: public.t_test_objrepdb7610)
2023-01-30 18:06:30,391 INFO  ReplicaDB:54 Total process time: 6126ms
```

**To Reproduce**
Steps to reproduce the behaviour:
1. setup Oracle to SQLite replication
2. start replicadb

**Expected behavior**
The replication works correctly

**Additional context**
Running on kubernetes, the SQlite database is stored on a PersistentVolume.

**Comment by shatteringlass** [comment]
I looked at the code and noticed [this TODO](https://github.com/osalvador/ReplicaDB/blob/master/src/main/java/org/replicadb/manager/SqlManager.java#L481) which makes it obvious that incremental replication is currently broken for SQLite.  

I tried adding `--sink-staging-schema main` to the options and now the error is slightly different:

```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: t_test_obj)
```

This seems to suggest that the sink table hasn't been created yet.

**Comment by shatteringlass** [comment]
To get around issues with staging schemas/tables, I've tested "complete" replication, which also results in errors:

```
2023-01-31 14:22:39,433 INFO  SqliteManager:337 Truncating sink table with this command: DELETE FROM t_test_obj 
2023-01-31 14:22:41,036 ERROR ReplicaDB:134 Got exception running ReplicaDB:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: t_test_obj)
```  

This seems to confirm that SQLiteManager is not taking care of the sink table creation before addressing it for truncate/insert operations.

**Comment by osalvador** [comment]
Hi @shatteringlass 

In ReplicaDB, the sink table must exist before running replication. In fact, in incremental mode, the sink table must exist and have a primary key column to detect the duplicate row and update it. [The documentation.](https://osalvador.github.io/ReplicaDB/docs/docs.html#incremental)

If the `public` schema is not valid for your database, you can use the `sink.staging.schema` parameter to define the schema in which the staging table should be created. This table is created based on the sink table, not the source table. 

You can review this example, the source database is a MongoDB but the sink parameters for SQLite are the same: 

```properties
######################## ReplicadB General Options ########################
mode=incremental
jobs=1
fetch.size=100
verbose=true
############################# Soruce Options ##############################
source.connect=mongodb+srv://*****.mongodb.net/catalog
source.table=products
source.columns={sku:1, ean:1,category:1, _id:0}
source.where={sku:84586818}
############################# Sink Options ################################
sink.connect=jdbc:sqlite:/Users/oscar.salvador/Documents/GitHub/ReplicaDB/conf/sqliteDb.db
sink.table=products
sink.columns=sku, ean, category
sink.staging.schema=main
```

Sink table DDL

```sql
create table products
(
    sku      integer constraint products_pk primary key,
    ean      TEXT,
    category TEXT
);
```

```
~/replicadb $> ./bin/replicadb --options-file ./conf/mongo2sqlite.conf                                                                   
2023-01-31 16:15:40,435 INFO  ReplicaDB:63 Running ReplicaDB version: 0.15.0
2023-01-31 16:15:40,440 INFO  ReplicaDB:66 Setting verbose mode DEBUG
2023-01-31 16:15:40,441 DEBUG ReplicaDB:67 ToolOptions{
	sourceConnect='mongodb+srv://*****.mongodb.net/catalog,
	sourceUser='null',
	sourcePassword='null',
	sourceTable='products',
	sourceColumns='{sku:1, ean:1,category:1, _id:0}',
	sourceWhere='{sku:84586818}',
	sourceQuery='null',
	sinkConnect='jdbc:sqlite:/Users/oscar.salvador/Documents/GitHub/ReplicaDB/conf/sqliteDb.db',
	sinkUser='null',
	sinkPassword='null',
	sinkTable='products',
	sinkStagingTable='null',
	sinkStagingSchema='main',
	sinkStagingTableAlias='null',
	sinkColumns='sku, ean, category',
	sinkDisableEscape=false,
	sinkDisableIndex=false,
	sinkDisableTruncate=false,
	sinkAnalyze=false,
	jobs=1,
	BandwidthThrottling=0,
	quotedIdentifiers=false,
	fetchSize=100,
	help=false,
	version=false,
	verbose=DEBUG,
	optionsFile='/Users/oscar.salvador/Desktop/conf/mongo2sqlite.conf',
	mode='incremental',
	sentryDsn='null',
	sourceConnectionParams={},
	sinkConnectionParams={},
	sourceFileFormat='null',
	sinkFileformat='null'}
2023-01-31 16:15:41,074 INFO  SqliteManager:230 Creating staging table with this command:  CREATE TABLE main.productsrepdb2310 AS SELECT sku, ean, category FROM products WHERE 1 = 0
2023-01-31 16:15:41,078 INFO  SqliteManager:337 Truncating sink table with this command: DELETE FROM main.productsrepdb2310
2023-01-31 16:15:41,081 INFO  ReplicaTask:35 Starting  TaskId-0
2023-01-31 16:15:41,342 INFO  MongoDBManager:166 TaskId-0: Using this clause to filter data from MongoDB: {"sku": 84586818, "stores": {"$elemMatch": {"storeId": 59}}}
2023-01-31 16:15:41,343 INFO  MongoDBManager:173 TaskId-0: Using this clause to project data from MongoDB: {"sku": 1, "ean": 1, "category": 1, "_id": 0}
2023-01-31 16:15:41,343 INFO  MongoDBManager:179 TaskId-0: Skip 0 data from source
2023-01-31 16:15:42,375 WARN  MongoDBRowSetImpl:116 The source columns/fields names are be defined by the first document returned by the cursor in this order: [sku, ean, category]
2023-01-31 16:15:42,380 INFO  SqliteManager:96 Inserting data with this command: INSERT INTO main.productsrepdb2310 (sku, ean, category) VALUES ( ?,?,? )
2023-01-31 16:15:42,385 INFO  ReplicaTask:67 A total of 1 rows processed by task 0
2023-01-31 16:15:42,444 INFO  SqlManager:315 Getting PKs for schema: null and table: products. Found.
2023-01-31 16:15:42,445 INFO  SqliteManager:272 Merging staging table and sink table with this command: INSERT INTO products (sku, ean, category )  SELECT sku, ean, category FROM productsrepdb2310 WHERE true ON CONFLICT  (sku ) DO UPDATE SET  sku = excluded.sku ,  ean = excluded. ean ,  category = excluded. category
2023-01-31 16:15:42,447 INFO  SqlManager:462 Dropping staging table with this command: DROP TABLE main.productsrepdb2310
2023-01-31 16:15:42,449 INFO  ReplicaDB:54 Total process time: 2023ms
```
