### ISSUE TITLE
Error reading files using JDK 17 - com.sun.rowset

### ISSUE THREAD

**Issue by ajkruse** [osalvador/ReplicaDB#125]
**Describe the bug**
Reading a source file with JDK 17 

ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: class org.replicadb.rowset.StreamingRowSetImpl (in unnamed module @0x5e922278) cannot access class com.sun.rowset.providers.RIOptimisticProvider (in module java.sql.rowset) because module java.sql.rowset does not export com.sun.rowset.providers to unnamed module @0x5e922278
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:115) [ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.0.jar:0.15.0]
Caused by: java.lang.IllegalAccessError: class org.replicadb.rowset.StreamingRowSetImpl (in unnamed module @0x5e922278) cannot access class com.sun.rowset.providers.RIOptimisticProvider (in module java.sql.rowset) because module java.sql.rowset does not export com.sun.rowset.providers to unnamed module @0x5e922278
        at org.replicadb.rowset.StreamingRowSetImpl.<init>(StreamingRowSetImpl.java:346) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.rowset.CsvCachedRowSetImpl.<init>(CsvCachedRowSetImpl.java:29) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.manager.file.CsvFileManager.init(CsvFileManager.java:207) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.manager.LocalFileManager.makeSourceConnection(LocalFileManager.java:52) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:103) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:43) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:15) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**

ReplicaDB:63 Running ReplicaDB version: 0.15.0

JAVA_HOME=/dint/java/jdk-17.0.6

echo "DATA" > /tmp/file1.csv
echo "" > /tmp/file2.csv

echo "mode=complete" >  /tmp/file.conf
echo "jobs=1" >> /tmp/file.conf
echo "verbose=true" >> /tmp/file.conf
echo "source.connect.parameter.columns.types=VARCHAR" >> /tmp/file.conf
echo "source.connect=file:///tmp/file1.csv" >> /tmp/file.conf
echo "sink.connect=file:///tmp/file2.csv" >> /tmp/file.conf

replicadb --options-file /tmp/file.conf

cat /tmp/file2.csv

**Expected behavior**
Source file is read and sink file is written.

JAVA_HOME=/dint/java/jdk1.8.0_351

echo "DATA" > /tmp/file1.csv
echo "" > /tmp/file2.csv

echo "mode=complete" >  /tmp/file.conf
echo "jobs=1" >> /tmp/file.conf
echo "verbose=true" >> /tmp/file.conf
echo "source.connect.parameter.columns.types=VARCHAR" >> /tmp/file.conf
echo "source.connect=file:///tmp/file1.csv" >> /tmp/file.conf
echo "sink.connect=file:///tmp/file2.csv" >> /tmp/file.conf

replicadb --options-file /tmp/file.conf

cat /tmp/file2.csv

**Additional context**
Only change is Java version from 8 to 17.

**Comment by osalvador** [comment]
Hi @ajkruse 

Currently, ReplicaDB is only compatible with Java 8, because we implement Rowset interfaces that since version 11 are private in the JDK. Sorry. 

Thanks!

**Comment by ajkruse** [comment]
Thanks @osalvador .
