### ISSUE TITLE
ReplicaDB exit code is not returned

### ISSUE THREAD

**Issue by qrollin** [osalvador/ReplicaDB#128]
An exception was raised by replicaDB, but it did not bubble up to my script. Everything is running on windows.

```
2023-02-22 15:25:47,172 ERROR ReplicaDB:134 Got exception running ReplicaDB:
com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK'. Cannot insert duplicate key in object 'table'. The duplicate key value is (test, test).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:300) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:133) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:907) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:802) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:742) ~[mssql-jdbc-11.2.3.jre8.jar:?]
	at org.replicadb.manager.SQLServerManager.mergeStagingTable(SQLServerManager.java:202) ~[ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.manager.SqlManager.postSinkTasks(SqlManager.java:508) ~[ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.manager.SQLServerManager.postSinkTasks(SQLServerManager.java:268) ~[ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:126) [ReplicaDB-0.15.0.jar:0.15.0]
	at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.0.jar:0.15.0]
2023-02-22 15:25:47,251 INFO  SqlManager:462 Dropping staging table with this command: DROP TABLE tablerepdb8810
2023-02-22 15:25:47,454 INFO  ReplicaDB:54 Total process time: 1503170ms
Replication done for table
```

The last line is from my script, it is printed with :
```
var processOptions = { stdio: ['ignore', process.stdout, process.stderr] };
var processArguments = ['--options-file', utils.getConfFilenameFromTable(tableName)];
var replicationProcess = spawn(replicadbExecutablePath, processArguments, processOptions);

return new Promise(function(resolve, reject) {
    replicationProcess.on('exit', function(code) {
        if(code === 0) {
            console.log("Replication done for table");
            resolve();
        } else {
            console.log("Replication failed for table with code " + code);
            reject();
        }
    });
});
```

I am pretty sure by looking at the code, that the exit code is properly propagated within replicaDB from such exception.
I also tested my part by spawning a batch file that call another one that `exit 1`, to make sure that if replicaDB fails, the `replicadb.cmd` would properly propagate to my part, and it works fine.

I'm having a hard time figuring what is happening. Do someone have an idea ?

**Comment by qrollin** [comment]
I might have found the issue here : the `replicadb.cmd` would not transmit the error code of the `call` launching the replicaDB.jar at the end of its execution, meaning that if replicaDB failed with an error code, my js script would not get the error code, and simply the one from the batch file running it (so 0).

It solved it by adding `exit %ERRORLEVEL%` at the end of the file.

@osalvador on what stack do you run your tests ? Are you aware of this kind of issue ?

**Comment by osalvador** [comment]
Thanks @qrollin for your contribution!
