### ISSUE TITLE
ReplicaDB not working for increment mode

### ISSUE THREAD

**Issue by abhid2004** [osalvador/ReplicaDB#134]
**Describe the bug**
ReplicaDB not working for increment mode. I want to compare set of rows and only replicate the differences

**To Reproduce**
My source and sync database is SolidDB. Conf file details below.

## complete, complete-atomic or incremental
mode=incremental

## integer greater than 0
jobs=1
fetch.size=100

## Adds a bandwidth cap for the replication in KB/sec.
#bandwidth.throttling=

## Help us to improve by activating usage analysis through the Sentry service.
# Or set up your own Sentry DSN
#sentry.dsn=https://400e0daa08c24a399b842048c409416f@o1002451.ingest.sentry.io/5962725

## Boolean; default is false
# quoted.identifiers=false
 verbose=true

############################# Source Options #############################
source.connect=jdbc:solid://127.0.0.0:1234/solidxx
source.user=xx
source.password=xx
source.table=xx
source.columns=x1,x2
source.where=x2>1
## or
#source.query=

## Optional extra JDBC parameters
source.connect.parameter.driver=solid.jdbc.SolidDriver

############################# Sink Options #############################
sink.connect=jdbc:solid://127.0.0.0:1234/solidxx
sink.user=xx
sink.password=xx
sink.table=xx
#sink.columns=x1,x2

## Optional extra JDBC parameters
sink.connect.parameter.driver=solid.jdbc.SolidDriver

## Staging options for incremental mode
# sink.staging.table=
# sink.staging.table.alias=
## or
sink.staging.schema=solidxxx

## Booleans; default are false
# sink.disable.escape=false
 sink.disable.truncate=true

**Expected behavior**

**Additional context**
Add any other context about the problem here. Running environment (cloud, on premise, java version..), source and sink technologies (Oracle, MySQL, Postgres...)

ERROR details:

2023-03-30 07:49:38,222 WARN  ManagerFactory:79 The database with scheme jdbc:solid: was not found. Trying  with standard JDBC manager
2023-03-30 07:49:38,224 WARN  ManagerFactory:79 The database with scheme jdbc:solid: was not found. Trying  with standard JDBC manager
2023-03-30 07:49:38,227 INFO  ReplicaTask:35 Starting  TaskId-0
2023-03-30 07:49:38,227 WARN  ManagerFactory:79 The database with scheme jdbc:solid: was not found. Trying  with standard JDBC manager
2023-03-30 07:49:38,228 WARN  ManagerFactory:79 The database with scheme jdbc:solid: was not found. Trying  with standard JDBC manager
2023-03-30 07:49:38,229 ERROR ReplicaTask:45 ERROR in TaskId-0 getting Source connection: Only the 'complete' mode is supported by Standard JDBC Manager.
2023-03-30 07:49:38,229 ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Only the 'complete' mode is supported by Standard JDBC Manager.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:115) [ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.0.jar:0.15.0]
Caused by: java.lang.UnsupportedOperationException: Only the 'complete' mode is supported by Standard JDBC Manager.
        at org.replicadb.manager.StandardJDBCManager.getDriverClass(StandardJDBCManager.java:27) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.manager.SqlManager.makeSourceConnection(SqlManager.java:183) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:103) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:43) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:15) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_265]
2023-03-30 07:49:38,237 ERROR ReplicaDB:156 java.lang.UnsupportedOperationException: Only the 'complete' mode is supported by Standard JDBC Manager.
2023-03-30 07:49:38,237 INFO  ReplicaDB:54 Total process time: 229ms

**Comment by abhid2004** [comment]
@osalvador can you help.

**Comment by osalvador** [comment]
Hi @abhid2004 

As you can see in the error log: `Only the 'complete' mode is supported by Standard JDBC Manager.`

Is also documented here https://osalvador.github.io/ReplicaDB/#compatible-databases

Thanks!

**Comment by abhid2004** [comment]
Thanks Oscar. While the tool helped me solve one problem case, we are a bit stuck with other.
Our application uses a change data capture tool to keep two database in sync. While CDC goes down, the data coming during that time doesn't sync and later we write sqls to find missing data and sync them manually. Very time consuming.
Do you recommend any other tool which can solve this problem. For example we can pass start date or unique id and from there it should create inserts and sync the data. We are using SolidDB.
Thanks,Abhishek Dey
    On Monday, April 17, 2023 at 04:05:27 PM GMT+5:30, Oscar Salvador Magallanes ***@***.***> wrote:  
 
 


Hi @abhid2004

As you can see in the error log: Only the 'complete' mode is supported by Standard JDBC Manager.

Is also documented here https://osalvador.github.io/ReplicaDB/#compatible-databases

Thanks!

**Comment by osalvador** [comment]
Sorry @abhid2004 , I am completely unaware of SolidDB capabilities and have not been able to find any of its documentation. Maybe you can use some ETL tool like Kettel or Talend?
