### ISSUE TITLE
couldn't sync sqlserver SHAPE field to geometry type in postgresql

### ISSUE THREAD

**Issue by Elmeslmaney** [osalvador/ReplicaDB#135]
**while trying to sync table from sqlserver that have geometry field named SHAPE to another table in postgresql field named geom got the following error**
`
2023-04-14 03:04:01,933 ERROR ReplicaTask:69 ERROR in TaskId-0 inserting data to sink table: [ERROR: parse error - invalid geometry
  Hint: "7C" <-- parse error at position 2 within geometry
  Where: COPY valves_pentab, line 1, column geom: "7C7F0000010C908EE472C6B41441907EFB526D764941"]
2023-04-14 03:04:02,041 ERROR ReplicaTask:69 ERROR in TaskId-2 inserting data to sink table: [ERROR: parse error - invalid geometry
  Hint: "7C" <-- parse error at position 2 within geometry
  Where: COPY valves_pentab, line 1, column geom: "7C7F0000010CA057CA72FEB31441EC0434096A764941"]
2023-04-14 03:04:02,165 ERROR ReplicaTask:69 ERROR in TaskId-3 inserting data to sink table: [ERROR: parse error - invalid geometry
  Hint: "7C" <-- parse error at position 2 within geometry
  Where: COPY valves_pentab, line 1, column geom: "7C7F0000010CB0B662BF77B41441287E8CE16E764941"]
2023-04-14 03:04:02,254 ERROR ReplicaTask:69 ERROR in TaskId-1 inserting data to sink table: [ERROR: parse error - invalid geometry
  Hint: "7C" <-- parse error at position 2 within geometry
  Where: COPY valves_pentab, line 1, column geom: "7C7F0000010C90D40928D1AB144104C58F1976794941"]
2023-04-14 03:04:02,256 ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: org.postgresql.util.PSQLException: ERROR: parse error - invalid geometry
  Hint: "7C" <-- parse error at position 2 within geometry
  Where: COPY valves_pentab, line 1, column geom: "7C7F0000010C908EE472C6B41441907EFB526D764941"
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:115) [ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.0.jar:0.15.0]
Caused by: org.postgresql.util.PSQLException: ERROR: parse error - invalid geometry
  Hint: "7C" <-- parse error at position 2 within geometry
  Where: COPY valves_pentab, line 1, column geom: "7C7F0000010C908EE472C6B41441907EFB526D764941"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.7.jar:42.3.7]
        at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1263) ~[postgresql-42.3.7.jar:42.3.7]
        at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1068) ~[postgresql-42.3.7.jar:42.3.7]
        at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49) ~[postgresql-42.3.7.jar:42.3.7]
        at org.replicadb.manager.PostgresqlManager.insertDataToTable(PostgresqlManager.java:134) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:65) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:15) ~[ReplicaDB-0.15.0.jar:0.15.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
2023-04-14 03:04:02,275 INFO  ReplicaDB:54 Total process time: 3636ms
`

**To Reproduce**
```
 read -r -d '' REPLICADB_CONFIGURATION << EOM
source.connect=jdbc:sqlserver://localhost:1433;database=dbname
source. User=sa
source. Password=<pd>
source. Table=<layername>
source. Columns=ID_Sys,Qism_Name,**SHAPE**
sink. Connect=jdbc:postgresql://localhost:5432/dbname
sink. User=postgres
sink. Password=1
sink. Table=dbname.valves
sink. Columns=id_sys,qism_name_ar,geom
sink.disable.escape=true
EOM
```

then 
run the following command 

` docker run \
    -e "REPLICADB_CONFIGURATION=${REPLICADB_CONFIGURATION}" \
    osalvador/replicadb`

**Expected behavior**
expected geom type handled  from sql server to postgresql and versa visca

**Comment by Elmeslmaney** [comment]
@osalvador 
@alexandra-zaharia 
@Jako81624 
@FrancescoTekapp 
could anyone help with that?

**Comment by osalvador** [comment]
Hi @Elmeslmaney 

To reproduce the behaviour we need; 
1. Source table DDL
2. Sink table DDL
3. Source SQLServer version
4. Sink Postgres version

Most likely these data types are not compatible between both databases and you will probably have to CAST them to Strings in the source to transform the string back to your data type in the target. As explained here: https://osalvador.github.io/ReplicaDB/docs/docs.html#47-mssql-server-connector

Thanks!

**Comment by Elmeslmaney** [comment]
thanks for your kind support will check it using SQL statement to cast the type manually and will be back to you.
