### ISSUE TITLE
Replication on Azure SQL Database 

### ISSUE THREAD

**Issue by prakash1303** [osalvador/ReplicaDB#16]
I am trying to replicate data across azure SQL databases (source and sink = Azure SQL). Getting below error while trying to run the command (mode - incremental ).  created a staging schema named staging and is part of the execution command
logs. 
Source table name = location schema = core
Sink table name = location schema =core_replica

2020-09-25 11:38:17,259 INFO ReplicaDB:42 Running ReplicaDB version: 0.8.7
2020-09-25 11:38:18,477 INFO SQLServerManager:129 Creating staging table with this command: SELECT * INTO staging.locationrepdb3310 FROM core_replica.location WHERE 0 = 1 
2020-09-25 11:38:18,566 INFO SqlManager:386 Truncating sink table with this command: TRUNCATE TABLE staging.locationrepdb3310
2020-09-25 11:38:18,650 INFO ReplicaTask:36 Starting TaskId-0

2020-09-25 11:38:19,793 INFO SQLServerManager:94 Perfoming BulkCopy into staging.locationrepdb3310 
2020-09-25 11:38:20,037 ERROR ReplicaTask:72 ERROR in TaskId-0 inserting data to sink table: The service has encountered an error processing your request. Please try again. Error code 4815.
2020-09-25 11:38:20,038 ERROR ReplicaDB:101 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: com.microsoft.sqlserver.jdbc.SQLServerException: The service has encountered an error processing your request. Please try again. Error code 4815.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]

1. Is Azure SQL supported for replication . I guess it should be as the drivers for SQL server and Azure SQL is the same
2. Is there a problem specifically due to bulk copy?

**Comment by prakash1303** [comment]
Few points on the above issue
1)Created the table definition in the sink schema using the same table definition script of the source table
2)Sink table has no rows
3)Can we print the entire exception instead of the table name which may help in further diagnosis?

**Comment by osalvador** [comment]
Hi prakash1303,

I found this on google:
https://mitchwheat.com/2020/04/04/sql-server-error-code-4815-bulk-insert-into-azure-sql-database/

Does this help you something?

**Comment by prakash1303** [comment]
Hi osalavdor,

The table definition script used in both the databases is the same. Hence on both source and sink column length, datatype is the same.
So that probably is not the reason , even though the error code might lead to one thinking that is the error.

**Comment by osalvador** [comment]
Hi @prakash1303,

- Can you share the version of the SQLServer databases? `select @@version as version`
- Can you share the table definition script you run on both databases?
- Can you share the `replicadb.conf` file or the command line arguments you have used when running replicadb?

**Comment by osalvador** [comment]
Issue closed due to inactivity
