### ISSUE TITLE
error login sqlserver

### ISSUE THREAD

**Issue by efcunha** [osalvador/ReplicaDB#168]
**Describe the bug**
A clear and concise description of what the bug is, with verbose log. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Source table DDL
2. Sink table DDL
3. ReplicaDB configuration `options-file`. 

2024-01-11 15:45:10,916 DEBUG ReplicaDB:67 ToolOptions{
        sourceConnect='jdbc:sqlserver://segware.cg120h1yldzn.us-east-1.rds.amazonaws.com:1433;database=SEGWARE_BOTTOM',
        sourceUser='ecunha',
        sourcePassword='****',
        sourceTable='CENTRAL_MONITORADA_HISTORICO,CENTRAL_MONITORADA_ORDEM_SERVICO,MYSECURITY_PRIVACY_POLICY,CENTRAL_MONITORADA_TABELA_HORARIO,MYSECURITY_PRIVACY_POLICY_USER,CENTRAL_MONITORADA_USUARIO,MYSECURITY_CUSTOM_MOSAIC,CENTRAL_MONITORADA_ZONA,MYSECURITY_PGM_CAMERAS,MYSECURITY_CUSTOM_ACCOUNT,MYSECURITY_FRIENDSHIP_CIRCLES,CENTRAL_MONITORADA_NOTIFICATION_HISTORY,CENTRAL_HISTORICO_ACESSO_WEBALARME,CENTRAL_MONITORADA_MOBILE,MYSECURITY_LOGGING,CLIENTES_BI,CENTRAL_MONITORADA_FUSO,MYSECURITY_LOGGING_ARCHIVE,MYSECURITY_HELPME,CENTRAL_MONITORADA,MYSECURITY_NOTIFICATION,CENTRAL_MONITORADA_CONTATO,tmp_central_monitorada_mobile_eurosec,snapshotOSAccounts,snapshotVTRAccounts,snapshotMSAccounts,sysdiagrams',
        sourceColumns='null',
        sourceWhere='null',
        sourceQuery='null',
        sinkConnect='jdbc:sqlserver://sqlserver-web.cg120h1yldzn.us-east-1.rds.amazonaws.com:1433;database=SEGWARE_BOTTOM',
        sinkUser='ecunha',
        sinkPassword='****',
        sinkTable='CENTRAL_MONITORADA_HISTORICO,CENTRAL_MONITORADA_ORDEM_SERVICO,MYSECURITY_PRIVACY_POLICY,CENTRAL_MONITORADA_TABELA_HORARIO,MYSECURITY_PRIVACY_POLICY_USER,CENTRAL_MONITORADA_USUARIO,MYSECURITY_CUSTOM_MOSAIC,CENTRAL_MONITORADA_ZONA,MYSECURITY_PGM_CAMERAS,MYSECURITY_CUSTOM_ACCOUNT,MYSECURITY_FRIENDSHIP_CIRCLES,CENTRAL_MONITORADA_NOTIFICATION_HISTORY,CENTRAL_HISTORICO_ACESSO_WEBALARME,CENTRAL_MONITORADA_MOBILE,MYSECURITY_LOGGING,CLIENTES_BI,CENTRAL_MONITORADA_FUSO,MYSECURITY_LOGGING_ARCHIVE,MYSECURITY_HELPME,CENTRAL_MONITORADA,MYSECURITY_NOTIFICATION,CENTRAL_MONITORADA_CONTATO,tmp_central_monitorada_mobile_eurosec,snapshotOSAccounts,snapshotVTRAccounts,snapshotMSAccounts,sysdiagrams',
        sinkStagingTable='null',
        sinkStagingSchema='null',
        sinkStagingTableAlias='null',
        sinkColumns='null',
        sinkDisableEscape=false,
        sinkDisableIndex=false,
        sinkDisableTruncate=false,
        sinkAnalyze=false,
        jobs=1,
        BandwidthThrottling=0,
        quotedIdentifiers=false,
        fetchSize=100,
        help=false,
        version=false,
        verbose=DEBUG,
        optionsFile='../conf/replicadb.conf',
        mode='incremental',
        sentryDsn='https://400e0daa08c24a399b842048c409416f@o1002451.ingest.sentry.io/5962725',
        sourceConnectionParams={},
        sinkConnectionParams={},
        sourceFileFormat='null',
        sinkFileformat='null'}
2024-01-11 15:45:11,053 INFO  Sentry:27 Sentry enabled
2024-01-11 15:45:11,092 WARN  SqlManager:482 No staging schema is defined, setting it as PUBLIC
2024-01-11 15:45:11,903 ERROR ReplicaDB:134 Got exception running ReplicaDB:
com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'ecunha'. ClientConnectionId:a8e65faa-4d89-40a0-9d42-c9e00aa16548
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:258) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:104) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5036) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3668) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:94) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3627) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2456) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2103) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1950) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1162) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:735) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_291]
        at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_291]
        at org.replicadb.manager.SqlManager.makeSinkConnection(SqlManager.java:259) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:105) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.SQLServerManager.createStagingTable(SQLServerManager.java:263) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.SqlManager.preSinkTasks(SqlManager.java:485) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:94) [ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.1.jar:0.15.1]
2024-01-11 15:45:11,985 ERROR ReplicaDB:156 com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'ecunha'. ClientConnectionId:975cc213-72f1-4fc5-b43a-d01c5f2ad122
2024-01-11 15:45:11,985 INFO  ReplicaDB:54 Total process time: 1084ms

**Expected behavior**

**Additional context**
Add any other context about the problem here. Running environment (cloud, on premise, java version..), source and sink technologies (Oracle, MySQL, Postgres...)
SQL Server Standard Edition 2014 to SQL Server Web Edition 2017

**Comment by MichalisDBA** [comment]
You can not add multiple tables yet. @osalvador said he had this on roadmap to-do.

You can use this as a workaround

https://github.com/osalvador/ReplicaDB/issues/27#issuecomment-862229297

**Comment by efcunha** [comment]
how to change the public schema in both source and sink by "dbo"

2024-01-15 13:50:02,157 INFO  Sentry:27 Sentry enabled
2024-01-15 13:50:02,217 WARN  SqlManager:482 No staging schema is defined, setting it as PUBLIC
2024-01-15 13:50:03,074 INFO  SQLServerManager:278 Creating staging table with this command:  SELECT * INTO public.MYSECURITY_PRIVACY_POLICYrepdb2410 FROM dbo.MYSECURITY_PRIVACY_POLICY WHERE 0 = 1
2024-01-15 13:50:03,078 ERROR ReplicaDB:134 Got exception running ReplicaDB:
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'public'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:711) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at org.replicadb.manager.SQLServerManager.createStagingTable(SQLServerManager.java:279) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.SqlManager.preSinkTasks(SqlManager.java:485) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:94) [ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.1.jar:0.15.1]
2024-01-15 13:50:03,135 INFO  SqlManager:462 Dropping staging table with this command: DROP TABLE public.MYSECURITY_PRIVACY_POLICYrepdb2410
2024-01-15 13:50:03,139 ERROR ReplicaDB:156 com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'public'.
2024-01-15 13:50:03,139 INFO  ReplicaDB:54 Total process time: 1327ms
