### ISSUE TITLE
Error when trying to copy colums with special characters

### ISSUE THREAD

**Issue by loicdescotte** [osalvador/ReplicaDB#169]
Hi,
I am using ReplicaDB to copy data from a mysql database to a postgresql database, I have issues with columns in the mysql source table that contain "+" and "-" chars in their name. 
I've tried to rename the columns in the sink : 

```
bin/replicadb --options-file dbreplica.conf --source-table "mytable" --sink-table "sink_my_table" --source-columns="name, 'rp-' as rpmoins,'rp+' as rpplus"
```

It failed with error : 
```
ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "'rp-'"
  Position: 67
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:115) [ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.1.jar:0.15.1]
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "'rp-'"
```

I have tried several formats to escape '+' and '-'  but always failed.

Thanks for your help

**Comment by loicdescotte** [comment]
The right way seems to be

```
" --source-columns="name,\`rp-\`,\`rp+\" --sink-columns="name,rpmoins,rpplus"
```

As it is working now, I am closing the issue
