### ISSUE TITLE
The connection string contains an empty host '[]'. 

### ISSUE THREAD

**Issue by sandeepraghu** [osalvador/ReplicaDB#172]
(venv) sandeepraghuvanshi@Sandeeps-MacBook-Pro ReplicaDB % docker run your_custom_image

2024-02-21 15:18:12,466 INFO  ReplicaDB:63 Running ReplicaDB version: 0.15.1
2024-02-21 15:18:12,469 INFO  ReplicaDB:66 Setting verbose mode INFO
2024-02-21 15:18:12,574 ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.lang.IllegalArgumentException: The connection string contains an empty host '[]'. 
        at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:1093) ~[mongodb-driver-core-4.8.1.jar:?]
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:359) ~[mongodb-driver-core-4.8.1.jar:?]
        at org.replicadb.manager.MongoDBManager.makeSinkConnection(MongoDBManager.java:99) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:105) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.MongoDBManager.truncateTable(MongoDBManager.java:494) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.manager.SqlManager.preSinkTasks(SqlManager.java:495) ~[ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:94) [ReplicaDB-0.15.1.jar:0.15.1]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.1.jar:0.15.1]
2024-02-21 15:18:12,576 INFO  ReplicaDB:54 Total process time: 113ms
(venv) sandeepraghuvanshi@Sandeeps-MacBook-Pro ReplicaDB %

**Comment by osalvador** [comment]
please use the issue template, we need more information to help you.

**Comment by sandeepraghu** [comment]
when i am running this command: docker run
-v /tmp/replicadb.conf:/home/replicadb/conf/replicadb.conf
osalvador/replicadb

i got this error message: Unable to find image 'osalvador/replicadb:latest' locally
latest: Pulling from osalvador/replicadb
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

so , i created my own docker image and run this command: docker run your_custom_image
so got this error: 
2024-02-21 15:18:12,466 INFO ReplicaDB:63 Running ReplicaDB version: 0.15.1
2024-02-21 15:18:12,469 INFO ReplicaDB:66 Setting verbose mode INFO
2024-02-21 15:18:12,574 ERROR ReplicaDB:134 Got exception running ReplicaDB:
java.lang.IllegalArgumentException: The connection string contains an empty host '[]'.
at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:1093) ~[mongodb-driver-core-4.8.1.jar:?]
at com.mongodb.ConnectionString.(ConnectionString.java:359) ~[mongodb-driver-core-4.8.1.jar:?]
at org.replicadb.manager.MongoDBManager.makeSinkConnection(MongoDBManager.java:99) ~[ReplicaDB-0.15.1.jar:0.15.1]
at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:105) ~[ReplicaDB-0.15.1.jar:0.15.1]
at org.replicadb.manager.MongoDBManager.truncateTable(MongoDBManager.java:494) ~[ReplicaDB-0.15.1.jar:0.15.1]
at org.replicadb.manager.SqlManager.preSinkTasks(SqlManager.java:495) ~[ReplicaDB-0.15.1.jar:0.15.1]
at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:94) [ReplicaDB-0.15.1.jar:0.15.1]
at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.15.1.jar:0.15.1]
2024-02-21 15:18:12,576 INFO ReplicaDB:54 Total process time: 113ms
