### ISSUE TITLE
source query not working with postgres

### ISSUE THREAD

**Issue by sidebaet** [osalvador/ReplicaDB#3]
Hi,

I'm trying to do a migration based on a source query from postgres to postgres with the following command : --source-query SELECT * FROM kp_room and I receive the following error : 

2020-01-10 10:37:11,681 DEBUG PostgresqlManager:298 Calculating the chunks size with this sql: SELECT  abs(count(*) / 4) chunk_size, count(*) total_rows FROM ( SELECT )
2020-01-10 10:37:11,690 ERROR ReplicaDB:83 Got exception running ReplicaDB:
org.postgresql.util.PSQLException: ERROR: subquery in FROM must have an alias
  Indice┬á: For example, FROM (SELECT ...) [AS] foo.
  Position┬á: 64
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2422) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2167) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.1.jar:42.2.1]
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224) ~[postgresql-42.2.1.jar:42.2.1]
        at org.replicadb.manager.PostgresqlManager.preSourceTasks(PostgresqlManager.java:299) ~[ReplicaDB-0.6.0.jar:0.6.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:59) [ReplicaDB-0.6.0.jar:0.6.0]

**Comment by osalvador** [comment]
Hi @sidebaet,

Thanks for the reply. You're right, PostgreSQL requires indicating an alias to the subquery.

I have fix the issue and created a new release 0.6.1 

```
$ bin/replicadb --mode=complete -j=1 \
--source-connect=jdbc:postgresql://127.0.0.1:5432/ \
--source-query='select * from dept' \
--sink-connect=jdbc:postgresql://127.0.0.1:5432/ \
--sink-table=dept2
2020-01-13 10:37:22,351 INFO  ReplicaDB:43 Running ReplicaDB version: 0.6.1
2020-01-13 10:37:22,574 INFO  ReplicaTask:36 Starting TaskId-0
2020-01-13 10:37:22,587 INFO  SqlManager:133 TaskId-0: Executing SQL statement: SELECT  * FROM (select * from dept) as T1 OFFSET ?
2020-01-13 10:37:22,588 INFO  SqlManager:140 TaskId-0: With args: 0,
2020-01-13 10:37:22,590 WARN  ConnManager:185 Options source-columns and sink-columns are null, getting from Source ResultSetMetaData: deptno,dname,loc
2020-01-13 10:37:22,591 INFO  PostgresqlManager:151 Copying data with this command: COPY dept2 (deptno,dname,loc) FROM STDIN WITH DELIMITER e'\x1f'  NULL '' ENCODING 'UTF-8'
2020-01-13 10:37:22,600 INFO  ReplicaDB:102 Total process time: 273ms
```

Please, if you have any other issue, don't forget to send us a comment.
