### ISSUE TITLE
Oracle to Postgres for geom column fails

### ISSUE THREAD

**Issue by ud20** [osalvador/ReplicaDB#5]
I am having issues dumping data from oracle to postgresql for geom columns. Here is the error:

 ERROR ReplicaDB:83 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: oracle/xdb/XMLType
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_232]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_232]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:74) [ReplicaDB-0.5.0.jar:0.5.0]
Caused by: java.lang.NoClassDefFoundError: oracle/xdb/XMLType
        at oracle.jdbc.driver.NamedTypeAccessor.getString(NamedTypeAccessor.java:351) ~[ojdbc8.jar:19.3.0.0.0]
        at oracle.jdbc.driver.GeneratedStatement.getString(GeneratedStatement.java:289) ~[ojdbc8.jar:19.3.0.0.0]
        at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:376) ~[ojdbc8.jar:19.3.0.0.0]
        at org.replicadb.manager.PostgresqlManager.insertDataToTable(PostgresqlManager.java:90) ~[ReplicaDB-0.5.0.jar:0.5.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:70) ~[ReplicaDB-0.5.0.jar:0.5.0]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:14) ~[ReplicaDB-0.5.0.jar:0.5.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_232]

I tried including the necessary libs but nothing worked. Thoughts?

**Comment by osalvador** [comment]
Hi @ud20 

As I can see in the stackTrace, geom columns are based on Oracle XMLType data type. You need the necessary required libs in the classpath: `xdb6` and `xmlparserv2`. 

In my tests, I found some memory leaks using this types of columns on the oracle drivers. So I recommend you to convert this columns to CLOBs using the `source.columns` parameter.

There is an entry in the documentation about this: https://osalvador.github.io/ReplicaDB/docs/docs.html#421-oracle-xmltype-columns

Hope this help.

**Comment by ud20** [comment]
That solved the issue. Thanks!
