### ISSUE TITLE
Replicate mediumblob fields from MySQL

### ISSUE THREAD

**Issue by osalvador** [osalvador/ReplicaDB#64]
My source mysql database have a couple of mediumblob fileds. How can replicate them to my sink (also Mysql) database?
As I'm getting this error:

```
2022-01-12 15:30:36,940 ERROR ReplicaTask:74 ERROR in TaskId-0 inserting data to sink table: (conn=77) Invalid utf8 character string: 'GSI���n%G"/�eHC�9����TQ�sC�����p?'
2022-01-12 15:30:36,941 ERROR ReplicaDB:136 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: java.sql.SQLTransientConnectionException: (conn=77) Invalid utf8 character string: 'GSI���n%G"/�eHC�9����TQ�sC�����p?'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:117) [ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.11.4.jar:0.11.4]
Caused by: java.sql.SQLTransientConnectionException: (conn=77) Invalid utf8 character string: 'GSI���n%G"/�eHC�9����TQ�sC�����p?'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:155) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:627) ~[mariadb-java-client-2.7.3.jar:?]
        at org.replicadb.manager.MySQLManager.insertDataToTable(MySQLManager.java:154) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:70) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:14) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Invalid utf8 character string: 'GSI���n%G"/�eHC�9����TQ�sC�����p?'
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:627) ~[mariadb-java-client-2.7.3.jar:?]
        at org.replicadb.manager.MySQLManager.insertDataToTable(MySQLManager.java:154) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:70) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:14) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
Caused by: java.sql.SQLException: Invalid utf8 character string: 'GSI���n%G"/�eHC�9����TQ�sC�����p?'
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1694) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1556) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readLocalInfilePacket(AbstractQueryProtocol.java:1798) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1562) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[mariadb-java-client-2.7.3.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:627) ~[mariadb-java-client-2.7.3.jar:?]
        at org.replicadb.manager.MySQLManager.insertDataToTable(MySQLManager.java:154) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:70) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at org.replicadb.ReplicaTask.call(ReplicaTask.java:14) ~[ReplicaDB-0.11.4.jar:0.11.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
```

_Originally posted by @pablotrin in https://github.com/osalvador/ReplicaDB/discussions/55_

**Comment by osalvador** [comment]
Hi @pablotrin,

I have solved this issue with binary data types to MySQL or MariaBD databases.

I hope this helps. 
Thank you.
