### ISSUE TITLE
syntax error during COPY 

### ISSUE THREAD

**Issue by spiralcb** [osalvador/ReplicaDB#67]
Hello, 

I'm using ReplicaDB to migrate SQL Server database to PostgreSQL. 

I receive the following error: 

2022-03-10 11:08:13,902 ERROR ReplicaTask:74 ERROR in TaskId-0 inserting data to sink table: ERROR: syntax error at or near "-"
  Position: 45
2022-03-10 11:08:13,902 ERROR ReplicaDB:136 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "-"
  Position: 45
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:117) [ReplicaDB-0.11.8.jar:0.11.8]
	at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.11.8.jar:0.11.8]
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "-"
  Position: 45
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1263) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:945) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:45) ~[postgresql-42.3.3.jar:42.3.3]
	at org.replicadb.manager.PostgresqlManager.insertDataToTable(PostgresqlManager.java:65) ~[ReplicaDB-0.11.8.jar:0.11.8]
	at org.replicadb.ReplicaTask.call(ReplicaTask.java:70) ~[ReplicaDB-0.11.8.jar:0.11.8]
	at org.replicadb.ReplicaTask.call(ReplicaTask.java:14) ~[ReplicaDB-0.11.8.jar:0.11.8]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

Do you think it's because some rows contains the - character in the source tables ?

Thanks in advance

**Comment by osalvador** [comment]
Hi @spiralcb ,

I don't think so... 

Could you share your ReplicaDB options file and the DDL of the source and sink table?

Thanks!

**Comment by osalvador** [comment]
Close due to inactivity
