### ISSUE TITLE
MSSQL reserved word 'FOR' as column name

### ISSUE THREAD

**Issue by galiciadecastro** [osalvador/ReplicaDB#9]
I'm not able to escape reserved words in the column name, such as [FOR]. I already tried square brackets, single and double quotes. Any idea how to overcome this?
Thanks

**Comment by osalvador** [comment]
Hi @galiciadecastro,

I can't reproduce your issue. Please send me your creation table DDL and the configuration file you are using in ReplicaDB.  This is my test environment:

MSSQL commands:
```sql
CREATE TABLE master.dbo.test_table (column1 varchar(1), "FOR" varchar(10));
INSERT INTO master.dbo.test_table (column1, [FOR]) VALUES ('1', 'valueFOR');
```

ReplicaDB config file: 
```properties
############################# ReplicadB Basics #############################
mode=complete
jobs=1
verbose=true
############################# Soruce Options #############################
source.connect=jdbc:sqlserver://localhost:1433
source.user=sa
source.password=1234
source.table=master.dbo.test_table
source.columns=column1, [FOR]
############################# Sink Options #############################
sink.connect=file:///Users/osalvador/Downloads/fileSink.csv
sink.connect.parameter.format.firstRecordAsHeader=true
```

Execution: 
```bash
$ ./bin/replicadb --options-file conf/replicadb.conf                               
2020-06-01 21:28:30,410 INFO  ReplicaDB:42 Running ReplicaDB version: 0.8.0
2020-06-01 21:28:30,413 INFO  ReplicaDB:46 Setting verbose mode
2020-06-01 21:28:30,416 DEBUG ReplicaDB:47 ToolOptions{
	sourceConnect='jdbc:sqlserver://localhost:1433',
	sourceUser='sa',
	sourcePassword='****',
	sourceTable='master.dbo.test_table',
	sourceColumns='column1, [FOR]',
	sourceWhere='null',
	sourceQuery='null',
	sinkConnect='file:///Users/osalvador/Downloads/fileSink.csv',
	sinkUser='null',
	sinkPassword='null',
	sinkTable='null',
	sinkStagingTable='null',
	sinkStagingSchema='null',
	sinkStagingTableAlias='null',
	sinkColumns='null',
	sinkDisableEscape=false,
	sinkDisableIndex=false,
	sinkDisableTruncate=false,
	sinkAnalyze=false,
	jobs=1,
	bandwidthThrottling=0,
	fetchSize=5000,
	help=false,
	version=false,
	verbose=true,
	optionsFile='conf/replicadb.conf',
	mode='complete',
	sourceConnectionParams={},
	sinkConnectionParams={format.firstRecordAsHeader=true}}
2020-06-01 21:28:30,431 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-06-01 21:28:30,435 DEBUG ManagerFactory:41 Trying with scheme: file:
2020-06-01 21:28:30,439 INFO  ReplicaTask:36 Starting TaskId-0
2020-06-01 21:28:30,439 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-06-01 21:28:30,439 DEBUG ManagerFactory:41 Trying with scheme: file:
2020-06-01 21:28:30,589 DEBUG SqlManager:212 No connection parameters specified. Using regular API for making connection.
2020-06-01 21:28:31,280 DEBUG SqlManager:131 TaskId-0: Using fetchSize for next query: 5000
2020-06-01 21:28:31,296 INFO  SqlManager:141 TaskId-0: Executing SQL statement: SELECT  column1, [FOR] FROM master.dbo.test_table where 0 = ?
2020-06-01 21:28:31,296 INFO  SqlManager:148 TaskId-0: With args: 0,
2020-06-01 21:28:31,335 INFO  CsvManager:276 Temp CSV file path: file:///Users/osalvador/Downloads/fileSink.csv.repdb.9277
2020-06-01 21:28:31,342 INFO  CsvManager:253 The final CSVFormat is: Delimiter=<,> QuoteChar=<"> RecordSeparator=<
> EmptyLines:ignored SkipHeaderRecord:true Header:[]
2020-06-01 21:28:31,450 INFO  CsvManager:343 Complete mode: creating and merging all temp files into: /Users/osalvador/Downloads/fileSink.csv
2020-06-01 21:28:31,452 INFO  ReplicaDB:124 Total process time: 1053ms

$ cat /Users/osalvador/Downloads/fileSink.csv                                  
column1," [FOR]"
1,valueFOR
```

**Comment by galiciadecastro** [comment]
Mode complete works without any problem. It occurs using incremental mode, so I guess is related to the merge operation.

MSSQL commands:
`CREATE TABLE master.dbo.test_table (column1 varchar(1), "FOR" varchar(10));
INSERT INTO master.dbo.test_table (column1, [FOR]) VALUES ('1', 'valueFOR');

CREATE TABLE master.dbo.test_table_rpt (column1 varchar(1), "FOR" varchar(10)
PRIMARY KEY(column1));`

ReplicaDB config file:
`######################## ReplicadB General Options ########################
mode=incremental
jobs=1
fetch.size=1000
verbose=true
############################# Soruce Options ##############################
source.connect=jdbc:sqlserver://localhost:1433;database=master
source.user=sa
source.password=1234
source.table=test_table
############################# Sink Options ################################
sink.connect=jdbc:sqlserver://localhost:1433;database=master
sink.user=sa
sink.password=1234
sink.table=test_table_rpt
sink.staging.schema=dbo`

Execution:
`C:\ReplicaDB-0.8.0>.\bin\replicadb --options-file conf/replicadb.conF
2020-06-02 10:34:03,823 INFO  ReplicaDB:42 Running ReplicaDB version: 0.8.0
2020-06-02 10:34:03,826 INFO  ReplicaDB:46 Setting verbose mode
2020-06-02 10:34:03,831 DEBUG ReplicaDB:47 ToolOptions{
        sourceConnect='jdbc:sqlserver://localhost:1433;database=master',
        sourceUser='sa',
        sourcePassword='****',
        sourceTable='test_table',
        sourceColumns='null',
        sourceWhere='null',
        sourceQuery='null',
        sinkConnect='jdbc:sqlserver://localhost:1433;database=master',
        sinkUser='sa',
        sinkPassword='****',
        sinkTable='test_table_rpt',
        sinkStagingTable='null',
        sinkStagingSchema='dbo',
        sinkStagingTableAlias='null',
        sinkColumns='null',
        sinkDisableEscape=false,
        sinkDisableIndex=false,
        sinkDisableTruncate=false,
        sinkAnalyze=false,
        jobs=1,
        bandwidthThrottling=0,
        fetchSize=1000,
        help=false,
        version=false,
        verbose=true,
        optionsFile='conf/replicadb.conF',
        mode='incremental',
        sourceConnectionParams={},
        sinkConnectionParams={}}
2020-06-02 10:34:03,851 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-06-02 10:34:03,855 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-06-02 10:34:03,912 DEBUG SqlManager:269 No connection parameters specified. Using regular API for making connection.
2020-06-02 10:34:04,677 INFO  SQLServerManager:114 Creating staging table with this command:  SELECT * INTO dbo.test_table_rptrepdb1410 FROM test_table_rpt WHERE 0 = 1
2020-06-02 10:34:04,697 INFO  SqlManager:383 Truncating sink table with this command: TRUNCATE TABLE dbo.test_table_rptrepdb1410
2020-06-02 10:34:04,701 INFO  ReplicaTask:36 Starting TaskId-0
2020-06-02 10:34:04,702 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-06-02 10:34:04,704 DEBUG ManagerFactory:41 Trying with scheme: jdbc:sqlserver:
2020-06-02 10:34:04,706 DEBUG SqlManager:212 No connection parameters specified. Using regular API for making connection.
2020-06-02 10:34:04,735 DEBUG SqlManager:269 No connection parameters specified. Using regular API for making connection.
2020-06-02 10:34:04,783 DEBUG SqlManager:131 TaskId-0: Using fetchSize for next query: 10000
2020-06-02 10:34:04,793 INFO  SqlManager:141 TaskId-0: Executing SQL statement: SELECT  * FROM test_table where 0 = ?
2020-06-02 10:34:04,794 INFO  SqlManager:148 TaskId-0: With args: 0,
2020-06-02 10:34:04,826 INFO  SQLServerManager:79 Perfoming BulkCopy into dbo.test_table_rptrepdb1410
2020-06-02 10:34:04,848 WARN  ConnManager:187 Options source-columns and sink-columns are null, getting from Source ResultSetMetaData: column1,FOR
2020-06-02 10:34:04,864 DEBUG SqlManager:331 Getting PKs for schema: null and table: test_table_rpt. Found.
2020-06-02 10:34:04,865 DEBUG SQLServerManager:154 colName: column1
2020-06-02 10:34:04,867 DEBUG SQLServerManager:154 colName: FOR
2020-06-02 10:34:04,868 INFO  SQLServerManager:175 Merging staging table and sink table with this command: MERGE INTO test_table_rpt trg USING (SELECT column1,FOR FROM dbo.test_table_rptrepdb1410 ) src ON  (src.column1= trg.column1 ) WHEN MATCHED THEN UPDATE SET  trg.FOR = src.FOR  WHEN NOT MATCHED THEN INSERT ( column1,FOR ) VALUES ( src.column1 , src.FOR  );
2020-06-02 10:34:04,871 ERROR ReplicaDB:101 Got exception running ReplicaDB:
com.microsoft.sqlserver.jdbc.SQLServerException: Sintaxis incorrecta cerca de la palabra clave 'FOR'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:711) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at org.replicadb.manager.SQLServerManager.mergeStagingTable(SQLServerManager.java:176) ~[ReplicaDB-0.8.0.jar:0.8.0]
        at org.replicadb.manager.SqlManager.postSinkTasks(SqlManager.java:518) ~[ReplicaDB-0.8.0.jar:0.8.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:94) [ReplicaDB-0.8.0.jar:0.8.0]
2020-06-02 10:34:04,884 INFO  SqlManager:472 Dropping staging table with this command: DROP TABLE dbo.test_table_rptrepdb1410
2020-06-02 10:34:04,890 INFO  ReplicaDB:124 Total process time: 1078ms`

**Comment by osalvador** [comment]
Thanks to @galiciadecastro, there is a bug with standard escape for column names in MS SQL Server. 

I'm looking at the standard function to escape these names, but it will take some time to test it. 

As workaround you can specify the name of the columns in the `source.columns` parameter, but they must match the ones in the sink. 

```
source.columns=column1, "FOR"
```

**Comment by osalvador** [comment]
Hi @galiciadecastro,

I have added a new release with a new parameter `quoted.identifiers`. 
When this parameter is set to `true`, ReplicaDB escape the columns name to standard ANSI SQL.
