### ISSUE TITLE
Empty `WHEN MATCHED THEN UPDATE SET` clause during `MERGE INTO`

### ISSUE THREAD

**Issue by qrollin** [osalvador/ReplicaDB#96]
**Describe the bug**
I am trying to replicate in incremental mode an association table where the PRIMARY KEY is a combination of all the columns of the table (only 2). In that case, the generated `MERGE INTO` query use an empty `WHEN MATCHED THEN UPDATE SET` clause

Logs :
```
2022-09-14 11:07:11,435 INFO  SqlManager:315 Getting PKs for schema: null and table: trips_delivery_numbers. Found.
2022-09-14 11:07:11,436 INFO  SQLServerManager:194 Merging staging table and sink table with this command: MERGE INTO trips_delivery_numbers trg USING (SELECT trip_id,delivery_number FROM dbo.trips_delivery_numbersrepdb8710 ) src ON  (src.trip_id= trg.trip_id AND src.delivery_number= trg.delivery_number ) WHEN MATCHED THEN UPDATE SET WHEN NOT MATCHED THEN INSERT ( trip_id,delivery_number ) VALUES ( src.trip_id , src.delivery_number  ); 
2022-09-14 11:07:11,482 ERROR ReplicaDB:136 Got exception running ReplicaDB:
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'WHEN'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:711) ~[mssql-jdbc-7.2.2.jre8.jar:?]
        at org.replicadb.manager.SQLServerManager.mergeStagingTable(SQLServerManager.java:195) ~[ReplicaDB-0.12.3.jar:0.12.3]
        at org.replicadb.manager.SqlManager.postSinkTasks(SqlManager.java:505) ~[ReplicaDB-0.12.3.jar:0.12.3]
        at org.replicadb.manager.SQLServerManager.postSinkTasks(SQLServerManager.java:261) ~[ReplicaDB-0.12.3.jar:0.12.3]
        at org.replicadb.ReplicaDB.processReplica(ReplicaDB.java:128) [ReplicaDB-0.12.3.jar:0.12.3]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:47) [ReplicaDB-0.12.3.jar:0.12.3]
```

**To Reproduce**
Options-file :
```
############################# Common Options ##############################
mode=incremental
jobs=4
fetch.size=500
bandwidth.throttling=0
verbose=false
############################# source Options ##############################
source.connect=**********
source.user=**********
source.password=**********
source.table=trips_delivery_numbers
source.where=trip_id IN (SELECT id FROM trips WHERE recorded_at >= '2022-08-01 00:00:00' AND recorded_at < '2022-08-08 00:00:00') AND
############################# sink Options ##############################
sink.connect=**********
sink.user=**********
sink.password=**********
sink.staging.schema=dbo
```

**Expected behavior**
When there is no column to update, there should be no `WHEN MATCHED THEN UPDATE`

**Additional context**
Both the source and sink databases are MSSQL

**Comment by osalvador** [comment]
Hi @qrollin 

In MSSQL it is not possible to update in the merge statement only the primary key columns. This should be an alert in ReplicaDB. 

You have two options here: 
- If you only wants to replicate the newly inserted records in the source table and the columns are all primary keys, use the complete mode but disable the truncate of the sink table using the `--sink-disable-truncate true` parameter or `sink.disable.truncate=true` property in the config file. 
- If the source table must have values that trigger the PK constraint in the sink table, add a new column in the sink table that allows the merge statement to work, for example a `replication_date` column
```
....
source.table=trips_delivery_numbers
source.columns=trip_id,delivery_number, getdate() as replication_date
source.where=trip_id IN (SELECT id FROM trips WHERE recorded_at >= '2022-08-01 00:00:00' AND recorded_at < '2022-08-08 00:00:00') AND
...
```

On the other hand, ReplicaDB should throw an exception in this case. 

Thank you for report.

**Comment by qrollin** [comment]
Unfortunately, neither solution are satisfactory in my specific case :
- The table being several million lines, using complete mode would put unnecessary stress on the ressources used for the replication.
- I cannot alter the data format.

The solution I used for the time being is forking this repository and modifying the way the "MERGE INTO" clause is generated, meaning I only insert the `WHEN MATCHED THEN UPDATE SET` when there is column to update (after filtering out all PKs)

**Comment by osalvador** [comment]
Hi @qrollin 

At the first point, you can replicate only the new rows, using the `where` clause, and disable the `truncate` statement to the sink table. This is the same as incremental mode, but is only valid if you are sure that no rows will cause a PK constraint error, without additional stress on resources. 

I don't understand what you want to do in the fork, could you share your fork with us or make a PR to review? 

Thanks!

**Comment by qrollin** [comment]
PR successfully merged, thank you 👍
